allowBuilds:
  esbuild: true
  simple-git-hooks: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@vitest/mocker@5.0.2'
  - '@vitest/spy@5.0.2'
  - vitest@5.0.2
  - eslint-plugin-jsdoc@65.0.0
