ssl_certificate /etc/letsencrypt/live/juya-test/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/juya-test/privkey.pem;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_session_cache shared:JuyaTestTLS:1m;
ssl_session_timeout 1d;
ssl_session_tickets off;
